---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: env-injector
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/finalizers"] # finalizers are needed for the owner reference of the webhook
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "update", "patch", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-injector
  namespace: injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: env-injector
subjects:
  - kind: ServiceAccount
    name: env-injector
    namespace: injector
roleRef:
  kind: ClusterRole
  name: env-injector
  apiGroup: rbac.authorization.k8s.io
