apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-injector
  namespace: injector
spec:
  selector:
    matchLabels:
      app: env-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: env-injector
    spec:
      containers:
      - name: env-injector
        image: toversus/env-injector:0.1.0
        imagePullPolicy: Always
        command: ["env-injector"]
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 10443
          name: https-webhook
        readinessProbe:
          periodSeconds: 1
          httpGet:
            scheme: HTTPS
            port: 10443
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      serviceAccountName: env-injector
      volumes:
      - name: config-logging
        configMap:
          name: config-logging
---
apiVersion: v1
kind: Service
metadata:
  name: env-injector
  namespace: injector
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 10443
  selector:
    app: env-injector
